### ISSUE TITLE
Video players get frozen

### ISSUE THREAD

**Issue by MALLER-LAGOON** [i-rinat/freshplayerplugin#159]
it doesn't matters if it's youtube, vimples, southpark.cc, or the facebook player, the video get frozen randomly, but particularly in the fullscreenmode and the console shows this message:

>[fresh] [error] ppb_message_loop_post_work_with_result, quit request received, no additional work could be posted

this kind of errors started since commits d5d20f0 and forward :/

**Comment by i-rinat** [comment]
Does this happen when you interact with the flash movie (click on right mouse button to open context menu), or does it happen by itself?

**Comment by MALLER-LAGOON** [comment]
Both :/

**Comment by i-rinat** [comment]
That's very strange, because patch d5d20f0 was made to fix freezes from context menu.

Flash context menu launches nested message loop without depth increase. So if such nested loop was launched on top of outermost loop with depth==1, nested loop was incorrectly treated as outermost loop, and then terminated. Subsequent calls of post_work_with_result() produced errors "quit request received, no additional work could be posted" because termination was already scheduled.

The patch fixes nested loop detection, and should therefore fix cause of the problem. Is there any chance you are testing some older version instead of a current one?

**Comment by MALLER-LAGOON** [comment]
nop, it always update to the latest commit on the master branch.

which is strange to me, is that happens only with the players, because the games on facebook works pretty fine.

**Comment by i-rinat** [comment]
I still can't reproduce freezing on my machine although I use Youtube a lot (mostly as background player, but sometimes in foreground too).

Could you find exact commit from which the bug started to appear?

**Comment by sunbriel** [comment]
Reporting this bug too. Both on my friend's Linux Mint Xfce 17.1 x64 laptop and my desktop LM Cinnamon 17.1 x64. Started happening recently, I would say less than a week ago. Video freezes while fullscreen. Sometimes immediately, sometimes randomly after some time has passed. Noticed this happening on Twitch.tv, but on other sites as well.

**Comment by MALLER-LAGOON** [comment]
i find it!!

the first conflicting commit was the 0a5e6ab, the previous 7a32884 works fine.

i'm not sure, but i guess it has to do with the function <code>ppb_core_call_on_main_thread</code> in <code>src/ppb_core.c</code>:
>const int depth = ppb_message_loop_get_depth(main_message_loop); 

which u change it for:

>const int depth = 1;

i'll try it latter and i told u if this modification fixes the error.

**Comment by MALLER-LAGOON** [comment]
@i-rinat i did the change from:

   > const int depth = 1;

to

    >const int depth = ppb_message_loop_get_depth(main_message_loop);

and the players recovers the stability.

**Comment by MALLER-LAGOON** [comment]
i did the change. it looks more stable, but after a minute or two, the error appears again.

this are the messages in the console:

> [fresh  7094] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0

> &#62;&#62;&#62; installPolicy shouldProcess() ...

> [fresh] [warning] ppb_graphics3d_create, some of GLX_ARB_create_context, GLX_ARB_create_context_profile, GLX_EXT_create_context_es2_profile missing

> &#62;&#62;&#62; installPolicy shouldProcess() ...
> &#62;&#62;&#62; installPolicy shouldProcess() ...

> [fresh] [error] ppb_message_loop_post_work_with_result, quit request received, no additional work could be posted

:/

**Comment by i-rinat** [comment]
@MALLER-LAGOON, please reconfigure with
`cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DTRACE_ALL=1 ..`
build and then run browser from terminal with redirection output to a file, like
`firefox > log`

I can't reproduce freezing on my machine, but maybe log file will give any clue.

**Comment by MALLER-LAGOON** [comment]
the log file was huge.
i'd uploaded to dropbox, here is the link: https://www.dropbox.com/s/mz6oqsuv743ii0b/Firefox-ERRORS_.txt.tar.gz?dl=0

**Comment by MALLER-LAGOON** [comment]
this other log, is when frozen while i was playing a facebook game. :/

now i wil get a log with the modified ppb_core.c, like a did before.
it was considerably more stable when the 
<code>depth = ppb_message_loop_get_depth(main_message_loop); </code>

when i get it, i'll upload it to dropbox like i did with the other 2 log files.

is it normal that the log file weight that much?

**Comment by i-rinat** [comment]
> it was considerably more stable when the

I hope it can be fixed without reverting that line, as it would break flash movies on Deezer.

> is it normal that the log file weight that much?

Yes, that's a trace file, it contains a record for almost every function in freshwrapper called. A number of megabytes per second is very common. (That's why it's disabled by default :-) )

**Comment by MALLER-LAGOON** [comment]
i'd notice that when the video freezes (in fullscreen mode), it still working in background, i try to minimize the firefox window and when i resize it, the video back with motion.
in youtube, for example, when freezes in a video and i do that thing of minimize and resize window, the video can work until it finishes, but if i try to get out of the fullscreen mode, it freezes again. and when the play back of those video finishes, the screen turns black, but the list is still playing in background, and due that i have compiz, i can change the window with the keyboard  key, and when go in this way to watch the firefox, the preview window shows me the youtube player working properly, but when go to the firefox screen it back to the nice black fullscreen with the player playing in the background.

**Comment by i-rinat** [comment]
So audio continues to play while image freezes? Or this is a new kind of freeze you discovered recently?
Is freezing related to the moment of switching between non-fullscreen and fullscreen mode (±1 sec)?

**Comment by MALLER-LAGOON** [comment]
yes, the audio continues while image freezes.
there is sometimes the freeze is total, and other times the audio are playing while the image is frozen.

there is no relative to the switch between fullscreen and non-fullscreen mode, it just happen while the player is in fullscreen mode, and i have no found any way to replicate the problem (right click, switch modes, etc.)

**Comment by toddfraser88** [comment]
This crash just happened for me aswell,

watching LGR - Operation Frog on youtube 
audio kept playing - but video frozen.

running kubuntu 14.10 with firefox 36.0.4 in a VMWare workstation VM

grabbed pepperflash manually from here
http://www.slackware.com/~alien/slackbuilds/chromium-pepperflash-plugin/pkg64/current/

freshplayer built from latest commit

**Comment by i-rinat** [comment]
I've seen similar freeze a few times, but as always, they are gone when I started to debug :-/

**Comment by toddfraser88** [comment]
it just happened again

**Comment by 05storm26** [comment]
Hi, I am also experiencing this issue. I just had a freeze when the fullscreen youtube player video stopped but the sound went on. I made a debug log file too, as you described. 

Here is the log file:

https://drive.google.com/file/d/0B3xv1WnYC6HSWFZQVVFMMVhhelU/view?usp=sharing

I used the most recent version (8a2b631968a44d5f2e97629dc16ce3b5b8188ada).

**Comment by MALLER-LAGOON** [comment]
yes, like 05storm26, since 8acb631 i had no more freezes. but i had to admit that the freshplayer remains a bit laggie. now i'm going to update to 52b52e7 and see what happens. :3

**Comment by i-rinat** [comment]
> i had no more freezes

There are another set of changes landed in `master` branch. Could you check recent version too? There were some changes related to message loop. It would be nice to ensure those changes a're not breaking it again.

**Comment by MALLER-LAGOON** [comment]
well, the freshplayer is not frozen playing videos. but, there is 2 observations, 1 is a bug, and the other i don't know how to call it.

the buggie one is on the facebook games.
when i try to send some invitations, i can't select all the users with the button "select all". this is the link to the game: https://apps.facebook.com/mutants_gg/

and the other one, i just when i go to the fullscreen mode, now turns to black and then reloads to the video or game, is just a second of delay. that could be not problem, if it sometimes the load image do not resize properly, filling a quarter of the screen.
this last one occurs very randomly, doesn't shows any console messages, , and disappears when i go out the fullscreen and back to the mode again.

**Comment by i-rinat** [comment]
> i can't select all the users with the button "select all"

I installed that app, but failed to find where button "select all" is. Could you give some hints?

> it sometimes the load image do not resize properly, filling a quarter of the screen.

What desktop environment are you using? (I know I asked that a number of times, but I forget it all the time.)

**Comment by MALLER-LAGOON** [comment]
I'm using XFCE 4.8.3

this is the select all button.

![select-all](https://cloud.githubusercontent.com/assets/7074901/7007313/f9a3a6f4-dc5e-11e4-8df7-cd9861c539f5.png)

and, when i try to rename the characters, it also give me some troubles. it just allow me to erase characters with the backspace and delete buttons, but i can't input any other key to rename the character. :/

![rename](https://cloud.githubusercontent.com/assets/7074901/7007338/56168fa0-dc5f-11e4-94a9-891bcecf22e1.png)

but, curiously, i do can copy from a leafpad or any other application and paste from the clipboard.

**Comment by i-rinat** [comment]
> but i can't input any other key to rename the character

That can be related to input method. There was a hack to make input method work even for windowless plugins, and it does work for complex inputs, but fails for ordinal latin characters. Disabled in 4886c2fc.

**Comment by i-rinat** [comment]
> this is the select all button.

Oh, found it. Unfortunately, I can't reproduce it, that checkbox select all items in the list.

**Comment by i-rinat** [comment]
@05storm26, @toddfraser88, did you have any freezes recently?

**Comment by MALLER-LAGOON** [comment]
in the last commit, both mentioned errors (select all and input) are fixed :)

**Comment by toddfraser88** [comment]
on some videos the video still freezes, but it's no longer a plugin crash, so I can just rewind the video to make it work again

**Comment by 05storm26** [comment]
No I did not have freezes since 19bd158. Right now i think i have d9e7cfb. I'm gonna upgrade to 2cda8cc now.

**Comment by i-rinat** [comment]
As original issue was solved, closing the issue.
