### ISSUE TITLE
Plugin crashes on first tab/window on youtube and needs refresh.

### ISSUE THREAD

**Issue by Barborica-Alexandru** [i-rinat/freshplayerplugin#165]
I built the plugin from the master branch today and whenever I start firefox and load a youtube video the plugin will freeze with the seek bar at the end and the page will need a refresh to start playing. In terminal the only output I get is:
NOT SANDBOXED
[fresh 11028] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
[fresh 11028] not implemented: PPB_VideoDecoder(Dev);0.16
But I doubt it has anything to do with the crash. The stable 0.23 version does not have this issue but fullscreen button hitboxes are misplaced.

**Comment by i-rinat** [comment]
I don't understand you well. Did plugin [crash](https://helpx.adobe.com/flash-player/kb/report-flash-player-crash/_jcr_content/main-pars/procedure_11/proc_par/step_0/step_par/img_0.img.png/14.PNG)? If yes, was crash instant, or it froze for about 45 sec and then crashed? In the second case it's the browser who terminates plugin process. Firefox does so if plugin doesn't respond for 45 seconds (dom.ipc.plugins.timeoutSecs). It's nevertheless a bug and needs to fixed anyway.

I've seen something similar to what you are describing, but can't reproduce it neither with browser restart, nor with running browser in incognito mode. On the other hand, I see that a lot in Opera 12 with Flash 11.2.

**Comment by Barborica-Alexandru** [comment]
The plugin does not crash completely, but it does not play the video on first attempt. If i press play when the plugin is frozen it will say an error has occured and show the youtube message: an error has occured please try again later.

**Comment by i-rinat** [comment]
> it will say an error has occured and show the youtube message: an error has occured please try again later.

That's exactly the behavior I see in Opera 12 with Flash 11.2.
Can't say for sure if it's related to freshwrapper code somehow. I'll try to dig more.

**Comment by Barborica-Alexandru** [comment]
It's possible considering that this does not happen in version 0.23. I'm running fedora 21 with intel integrated graphics 2000 and 1.18 driver. Latest firefox.

**Comment by i-rinat** [comment]
Can you bisect history to find out which commit is causing malfunctioning? Looks like issue is well reproducible on your machine.

**Comment by Barborica-Alexandru** [comment]
ppb_var: construct wrapper objects by means of npn.createobject

This is the commit that breaks it.

**Comment by i-rinat** [comment]
Well, I can't find anything wrong in 1defbf0d0e28172a7de80d47e790b757a2b00098, but there were other calls that should be done on a browser thread. Those are addressed in 4890f558396252ca9017caa7f20e442f398590cf, 4718845cb5720d9997f30333d90c045c455b1e19, and 5dc17725107dec50d99df1db61a683087253a071.

I'm not sure, but maybe 1defbf0d0e28172a7de80d47e790b757a2b00098 revealed bug, and I hope others fixed it. Could you check again with recent version?

**Comment by Barborica-Alexandru** [comment]
Issue still happens on [5dc1772]. 
[aec87db] is the last version which works correctly.

**Comment by i-rinat** [comment]
> Can you modify a recent build and remove the lines added in 1defbf0?

Yep: https://github.com/i-rinat/freshplayerplugin/tree/tmp-revert-1defbf0

**Comment by Barborica-Alexandru** [comment]
Ok so the modified 1defbf0 doesn't work because in aec87db the line "retain_np_object(res.value.objectValue);" is "npn.retainobject(res.value.objectValue); // TODO: call on main thread?". After I changed it in the reverted build it started working fine again. So the issue is a combination of the changes made in 1defbf0 and the line "retain_np_object(res.value.objectValue);" which was later added.

**Comment by i-rinat** [comment]
Hmm, but I can't change it back again, that will bring back crashes at plugin termination.

Perhaps there is a timing issue. Calling NPN functions on browser thread involves dancing with nested message loops, which can reorder calls, which in turn causes race condition.

**Comment by i-rinat** [comment]
I found a way to reproduce the issue, and patch f04e590bb39bdccc3cd8dcd1eae9df39684aac36 makes it disappear. Patch moves wrapper object creation to NPP_GetValue, i.e. on demand. Thus always will be called on browser thread, so there should be no race condition anymore.

Could you check again?

**Comment by Barborica-Alexandru** [comment]
Yes it works now, great work!
