### ISSUE TITLE
Error with vaapi decoding

### ISSUE THREAD

**Issue by gipawu** [i-rinat/freshplayerplugin#204]
I tried new hardware decoding feature, but in Youtube I get black screen (just audio working) and this error:
```
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_0_36
libva info: va_openDriver() returns 0
NOT SANDBOXED
[fresh  6570] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
[fresh] [error] [NP] caught Xlib error 8
[fresh] [error] [NP] caught Xlib error 8
[fresh] [error] [NP] caught Xlib error 3
[fresh] [error] [NP] caught Xlib error 3
[fresh] [error] [NP] caught Xlib error 3
[fresh] [error] [NP] caught Xlib error 3
[fresh] [error] [NP] caught Xlib error 3
[fresh] [error] [NP] caught Xlib error 3
[fresh] [error] [NP] caught Xlib error 3
[fresh] [error] [NP] caught Xlib error 3
[fresh] [error] [NP] caught Xlib error 3
[fresh] [error] [NP] caught Xlib error 3
[fresh] [error] [NP] caught Xlib error 2
[fresh] [error] [NP] caught Xlib error 2
[fresh] [error] [NP] caught Xlib error 2
...
...
[fresh] [error] [NP] caught Xlib error 2 (INFINITE)
...
```
I use a Nvidia 8600m GT with Nvidia proprietary drivers.
Do you have any clue? And thanks for your work.

EDIT: Well, I have the same problem disabling hardware decoding too. It's the 0.3 version that brought some troubles, 0.2.4 version worked fine.

**Comment by dacrhu** [comment]
Pls check this:
https://github.com/i-rinat/freshplayerplugin/issues/201

**Comment by gipawu** [comment]
Thank you, using last git version it works fine now.
But now I noticed another problem.
It seems there is a memory leak in hardware decoding: when i switch video resolution on Youtube (also switching to LOWER resolution), the GPU memory keeps increasing, until the memory gets full and I get broken video. In console i get  ``` vdpau_video: VdpPresentationQueueBlockUntilSurfaceIdle(): status 3: An invalid handle value was provided ```

**Comment by i-rinat** [comment]
@gipawu,
I've found missing `avcodec_close()` call, which is fixed in 59a5025a97940674492bc5db2c5254586f752a8a. Could you test again?

**Comment by gipawu** [comment]
Unfortunately, atleast for me, the problem is still present.
I noticed that first switching time to a specific resolution is longer that subsequent switching times to same resolution. I suspect that Youtube (or freshplayer plugin I don't know...) does not "free" completely a video stream on res switching.
So, observing GPU memory usage, the video memory used by a video stream at whatever resolution, is not freed on resolution switch (and so video stream switch).
As I said before, I don't know if the problem is related to freshplayerplugin or something else (such as video drivers, ffmpeg, Youtube ,etc.)

**Comment by i-rinat** [comment]
Yep, indeed. On every seek PepperFlash resets current decoder and creates a new one. It destroys all them only when instance is terminated. I'll look at how it could be mitigated.

**Comment by i-rinat** [comment]
Surprisingly, Intel GPU drivers don't care too much about allocated resources: numbers in `intel_gpu_top` output are not increasing.

**Comment by i-rinat** [comment]
Made decoder to deallocate resources when `_reset()` is called. (667bf9e00ba96520ad164f821f8e608291d88cef)

**Comment by i-rinat** [comment]
Could you check again with the recent version? A few hwdec fixes were added in bf84892e0eb753604b9a2f517966ca92fbc3329b and some previous commits.

**Comment by i-rinat** [comment]
The issue was involving vaapi->vdpau translation layer, vdpau-va-driver. Since freshwrapper now have direct VDPAU support, this is not relevant anymore.
