### ISSUE TITLE
Chromebook's flash used by firefox works on test but fails in real life 

### ISSUE THREAD

**Issue by Enerccio** [i-rinat/freshplayerplugin#377]
I have extracted and installed pepper flash from chrome os backup image. When I try http://drmtest2.adobe.com:8080/SVP/SampleVideoPlayer_FP.html# with http://drmtest2.adobe.com:8080/Content/anonymous.f4v everything works just fine and train video plays.

Here is log: 

Starts to get video metadata at Mon Jul 16 13:00:55 GMT+0200 2018
DRMContentData received on Mon Jul 16 13:00:55 GMT+0200 2018
authenticationMethod = anonymous
ServerURL = http://drmtest2.adobe.com:8080
license ID = 43345AEF-52FF-3F20-90FF-ABDC98A2E3E4
Local voucher...
Load local voucher complete event received on Mon Jul 16 13:00:56 GMT+0200 2018
voucher not found in local voucher store.
DownloadVoucherComplete event received on Mon Jul 16 13:00:56 GMT+0200 2018

customPolicies : 
policies.Slippery = Slope_Let's_Fall_Down_It
policies.playbackMode = all
policies.Giant = SuperDuperPanda
policies.Sound of one hand clapping = 
policies.DRMTEST2 = 
startDate = null
endDate = null
offlineLeaseStartDate = Mon Jul 16 13:00:56 GMT+0200 2018
offlineLeaseEndDate = Mon Jul 16 14:00:56 GMT+0200 2018
playbackTimeWindow = null 
-------------
Start to play content on Mon Jul 16 13:00:56 GMT+0200 2018
-------------

DRMStatus event received on Mon Jul 16 13:00:57 GMT+0200 2018

customPolicies : 
policies.Slippery = Slope_Let's_Fall_Down_It
policies.playbackMode = all
policies.Giant = SuperDuperPanda
policies.Sound of one hand clapping = 
policies.DRMTEST2 = 
startDate = null
endDate = null
offlineLeaseStartDate = Mon Jul 16 13:00:56 GMT+0200 2018
offlineLeaseEndDate = Mon Jul 16 14:00:56 GMT+0200 2018
playbackTimeWindow = null 

But when I try to play real life web service (wwe network) it seems like it wants to start but then it fails.
In console, firefox will output:

".ARNING:flash/platform/pepper/pep_url_request_info.cpp(219)] Missing colon in HTTP header line "
[WARNING:flash/platform/pepper/pep_url_request_info.cpp(195)] Illegal HTTP header field: "User-Agent".
[WARNING:flash/platform/pepper/pep_url_request_info.cpp(195)] Illegal HTTP header field: "Connection".

over and over.

**Comment by Enerccio** [comment]
Maybe it needs `not implemented: PPB_BrokerTrusted;0.3`?

**Comment by i-rinat** [comment]
> Missing colon in HTTP header line
> Illegal HTTP header field: "User-Agent".

Those messages look mysterious. I remember similar messages, but that issue was fixed years ago. What version of freshplayerplugin do you use? Did you try the latest one from the repo?

Is there any other site with similar error, preferably without required regustrations?

> Maybe it needs `not implemented: PPB_BrokerTrusted;0.3`?

That's unlikely. It's somehow related to privilege separation and sandboxing. (Also, I have no idea how to implement that from documentation only. It's to vague.)

**Comment by Enerccio** [comment]
This is with latest git build built from aur (arch linux user repository): https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=freshplayerplugin-git

Still not working and same set of messages.
```
[Parent 13164, Gecko_IOThread] WARNING: pipe error (145): Connection reset by peer: file /build/firefox/src/mozilla-unified/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
NOT SANDBOXED
[fresh 13317] not implemented: PPB_OpenGLES2VertexArrayObject;1.0
[fresh 13317] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
[fresh 13317] not implemented: PPB_BrokerTrusted;0.3
[fresh 13317] not implemented: PPB_BrokerTrusted;0.3
[ERROR:flash/platform/pepper/pep_shader_factory.cpp(408)] Compilation failed: 0:1(1): error: syntax error, unexpected $end

[ERROR:flash/platform/pepper/pep_shader_factory.cpp(408)] Compilation failed: 0:1(1): error: syntax error, unexpected $end
```
This shows when loading video.
```
[WARNING:flash/platform/pepper/pep_url_request_info.cpp(195)] Illegal HTTP header field: "User-Agent".
[WARNING:flash/platform/pepper/pep_url_request_info.cpp(195)] Illegal HTTP header field: "Connection".
".ARNING:flash/platform/pepper/pep_url_request_info.cpp(219)] Missing colon in HTTP header line "
[WARNING:flash/platform/pepper/pep_url_request_info.cpp(195)] Illegal HTTP header field: "User-Agent".
[WARNING:flash/platform/pepper/pep_url_request_info.cpp(195)] Illegal HTTP header field: "Connection".
".ARNING:flash/platform/pepper/pep_url_request_info.cpp(219)] Missing colon in HTTP header line "
[WARNING:flash/platform/pepper/pep_url_request_info.cpp(195)] Illegal HTTP header field: "User-Agent".
```

**Comment by i-rinat** [comment]
Yeah, eventually.
